name: Rust Tests

on:
  workflow_call:

jobs:
  test:
    name: Test Suite (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate GitHub App Token
        id: app_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.THIS_GITHUB_APP_ID }}
          private-key: ${{ secrets.THIS_GITHUB_APP_PRIVATE_KEY }}

      - name: Configure Git with App Token
        run: |
          git config --global url."https://x-access-token:${{ steps.app_token.outputs.token }}@github.com/".insteadOf "https://github.com/"

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: rust-test-${{ matrix.os }}

      - name: Run check
        run: cargo check --all-targets --all-features

      - name: Run tests
        run: cargo test --all-features

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        with:
          key: rust-lint

      - name: Run fmt
        run: cargo fmt --all --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
